"""
冬 · 状态系统 — compat 兼容层
从各子文件 re-export 所有符号，保持 from dong.status import * 兼容
"""
# ---- 从 manager 导入 ----
from .manager import (
    _status_manager,
    _StatusProxy,
    _status,
    _voice_state,
    StatusManager,
    UserStatus,
    HormoneSystem,
    weather_system,
    weather_cache,
    LIFE_FRAGMENTS,
    # 兼容函数
    load_last_day,
    save_last_day,
    load_status,
    save_status,
    load_global_state,
    save_global_state,
    update_fatigue,
    update_mood,
    detect_mood_change,
    check_sleep,
    get_status_prompt,
    get_status_raw,
    should_trigger_voice,
    get_voice_state_prompt,
    apply_mood_ripple,
    note_interaction,
    update_mood_cycle,
    update_pushpull,
    get_cycle_prompt,
    get_cycle_proactive_bonus,
    get_pushpull_prompt,
    get_pushpull_proactive_bonus,
    process_offline_life,
    get_offline_prompt,
    clear_offline_events,
    apply_external_mood,
    save_day_summary,
    get_sleep_transition,
    get_bedtime_message,
    get_morning_message,
    check_weather_care,
    reset_daily_flags,
    get_hormone_snapshot,
    update_hormones,
    apply_amygdala_spike,
    detect_hormone_event,
    add_delayed_proactive,
    pop_due_delayed_events,
    set_proactive_signal,
    get_pending_proactive_signal,
    _ai_hormone_correct,
    _sync_status_from_manager,
    maybe_life_fragment,
    get_time_sense_prompt,
    get_date_awareness_prompt,
    get_habits_prompt,
    should_terminate_conversation,
)

# ---- 从 weather 导入兼容函数 ----
from .weather import (
    WeatherSystem,
    init_weather,
    get_weather_data,
    should_refresh_weather,
    build_weather_system,
)

# ---- 从 _core 导入内核函数 ----
from ._core import (
    compute_drives,
    compute_mood_vector,
    mood_vector_to_text,
    _call_ai_simple,
    _clamp,
)

# ---- 从 hormones 导入 ----
from .hormones import HormoneState

__all__ = [
    # 核心类
    "StatusManager",
    "WeatherSystem",
    "UserStatus",
    "HormoneSystem",
    "HormoneState",
    "weather_system",
    "weather_cache",
    # 管理器实例
    "_status_manager",
    # 兼容全局变量
    "_status",
    "_voice_state",
    "LIFE_FRAGMENTS",
    # weather 兼容函数
    "init_weather",
    "get_weather_data",
    "should_refresh_weather",
    "build_weather_system",
    # 内核函数
    "compute_drives",
    "compute_mood_vector",
    "mood_vector_to_text",
    "_call_ai_simple",
    "_clamp",
    # 兼容旧接口函数
    "load_last_day",
    "save_last_day",
    "load_status",
    "save_status",
    "load_global_state",
    "save_global_state",
    "update_fatigue",
    "update_mood",
    "detect_mood_change",
    "check_sleep",
    "get_status_prompt",
    "get_status_raw",
    "should_trigger_voice",
    "get_voice_state_prompt",
    "apply_mood_ripple",
    "note_interaction",
    "update_mood_cycle",
    "update_pushpull",
    "get_cycle_prompt",
    "get_cycle_proactive_bonus",
    "get_pushpull_prompt",
    "get_pushpull_proactive_bonus",
    "process_offline_life",
    "get_offline_prompt",
    "clear_offline_events",
    "apply_external_mood",
    "save_day_summary",
    "get_sleep_transition",
    "get_bedtime_message",
    "get_morning_message",
    "check_weather_care",
    "reset_daily_flags",
    "get_hormone_snapshot",
    "update_hormones",
    "apply_amygdala_spike",
    "detect_hormone_event",
    "add_delayed_proactive",
    "pop_due_delayed_events",
    "set_proactive_signal",
    "get_pending_proactive_signal",
    "_ai_hormone_correct",
    "_sync_status_from_manager",
    "maybe_life_fragment",
    "get_time_sense_prompt",
    "get_date_awareness_prompt",
    "get_habits_prompt",
    "should_terminate_conversation",
]